#!/bin/bash
#g++ publish.cpp -o publish -lpaho-mqtt3c
#g++ subscribe.cpp -o subscribe -lpaho-mqtt3c
g++ ethan_publish.cpp -o ethan_publish -lpaho-mqtt3c
g++ ethan_subscribe.cpp -o ethan_subscribe -lpaho-mqtt3c
